# gpx2video icons
install(FILES 48x48/apps/com.progweb.gpx2video.png DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/48x48/apps)
install(FILES scalable/apps/gpx2video.svg DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/scalable/apps)
install(FILES scalable/apps/com.progweb.gpx2video.svg DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/scalable/apps)

