from ubuntu:22.04

run apt-get update && apt-get --yes --force-yes dist-upgrade

run apt-get install --yes --force-yes --no-install-recommends \
	vim \
	procps \
	\
	build-essential \
	cmake pkg-config \
	\
	libevent-dev libssl-dev libcurl4-gnutls-dev \
    libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libswresample-dev libswscale-dev \
    libopenexr-dev libopenimageio-dev libgeographic-dev libcairo2-dev

